project_id = "ucaqbhmyutlnitnedowk"

[functions.chess-coach]
verify_jwt = false

[functions.generate-custom-rules]
verify_jwt = false

[functions.generate-chess-variant-code]
verify_jwt = false

[functions.live-eval]
verify_jwt = false
