// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucaqbhmyutlnitnedowk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYXFiaG15dXRsbml0bmVkb3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTUwMDgsImV4cCI6MjA3NDU5MTAwOH0.nq7LZAjKUaP0rhaG_D2YOaLbt_I3GtJaGmpIXs7fvgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});