// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xovkrhndndiduesrrfti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdmtyaG5kbmRpZHVlc3JyZnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTM5NTYsImV4cCI6MjA3MDA2OTk1Nn0.zjatDveZGwUHaeruICO9SzNi4HQ--PRVUDqgiD4J9WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});